### ISSUE TITLE
Error after launching sgCheckup

### ISSUE THREAD

**Issue by NSi1974** [goldfiglabs/sgCheckup#1]
Hi,

I've decide to test sgCheckup as it seems very helpful for me, especially with the reporting fonctionnality.
I'm using the binary version on an Ubuntu.
I've set up an AWS profile.
Here is the error message I get after launching sgCheckup :

ubuntu@ip-172-17-13-117:~/sgCheckup_bin$ sudo ./sgCheckup
INFO[0000] Running postgres
INFO[0001] Waiting for postgres to be healthy
INFO[0033] Postgres is healthy
INFO[0033] Checking for introspector image
INFO[0035] Initializing introspector
INFO[0038] Running introspector with service spec ec2=SecurityGroups,NetworkInterfaces
INFO[0038] Introspector run may take a few minutes
INFO[0050] # Report Rows: 0
panic: Failed to load metadata: Query for most recent import job found no results

goroutine 1 [running]:
main.main()
        /Users/vikrum/dev/sgCheckup/main.go:469 +0x1613

Have you any idea of the problem ?
Thank you in advance !

Nicolas

**Comment by vikrum** [comment]
Hi - could you please try re-running it without `sudo` ? It doesn't need to run as root and that might be interfering with the credentials being picked up. Let me know and I can help debug further if the problem persists.

**Comment by NSi1974** [comment]
Hi Vikrum,
It's all good now, thanks to your comment.
I only needed to add a credential in my root account. All is OK now 👍🏻
